version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:14-alpine
    container_name: music_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_db
    ports:
      - "5432:5432" # Expõe a porta do Postgres para o seu computador
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Serviço de Armazenamento de Objetos (S3 local)
  minio:
    image: minio/minio
    container_name: music_minio
    environment:
      MINIO_ROOT_USER: minioadmin # Login do MinIO
      MINIO_ROOT_PASSWORD: minioadmin # Senha do MinIO
    ports:
      - "9000:9000" # Porta da API do MinIO
      - "9001:9001" # Porta do Console Web do MinIO
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data: